### ISSUE TITLE
[bug] spinner가 계속 돌아요

### ISSUE THREAD

**Issue by young-do** [connect-foundation/2019-05#128]
## 체크포인트
 - [ ] first task
 - [ ] second task
 - [ ] third task
OS: macOS 10.15.1
Browser: 버전 78.0.3904.108(공식 빌드) (64비트)

/match url로 들어갔을 때, spinner가 계속 돕니다.

그나저나 어떤 이유로 스피너가 계속 돌고 있는지 모르겠어요..!

**Comment by jongnan** [comment]
리뷰 감사드립니다.

해당 버그는 수정하였습니다.
